= Table of contents

LogSense supports wide array of log sources through two popular
protocols: *syslog* and *fluentd*. Either a generic library or a
dedicated solution can be used with the only requirement being providing
`CUSTOMER_TOKEN` (available in *Customer Tokens* section of the user portal) which
allows to identify and authorize the data stream.

In case of choice between using `fluentd` and `syslog` protocols - it is
recommended to go with `fluentd` due to a much better support of
structured logs and better troubleshooting capabilities.

== Generic setup
* <<nc-test.adoc#, One-liner test command using `nc`>>
* <<linux.adoc#, Syslog protocol via `syslog-ng`>>
* <<fluentd.adoc#, Generic `fluentd` forwarder config>>
* <<fluentd-container.adoc#, Docker `fluentd` forwarder>>

== Dedicated configuration

=== Programming languages and application servers

* <<java.adoc#,Java, Scala, Clojure, Kotlin, any other *JVM*-based technology logs>>
* <<java.adoc#javaee, Java EE Web Application logs>>
* <<java-tracing.adoc#, Java Tracing and performance monitoring>>
* <<nodejs.adoc#, NodeJS>>
* <<dot-net.adoc#, .NET>>
* <<python.adoc#, Python>>


=== Cloud Services
* <<aws-cloudwatch.adoc#, Collecting logs from EC2 instances, CloudTrail, Route 53, AWS Lambda and others>>

=== Operating Systems and services
* <<windows.adoc#,Windows Event Logs (including both operating system and services, such as
e.g. MS SQL)>>
* <<linux.adoc#,Linux logs using `syslog-ng`>>
* <<apache.adoc#, Apache HTTP Server logs using `fluentd`>>
* <<nginx.adoc#, nginx logs using `fluentd`>>
* <<kubernetes.adoc#, Kubernetes cluster logs using `fluentd`>>
* <<docker.adoc#, Docker containers logs>>


=== Other
* Do you have an use case not covered by the instructions? mailto:testing@logsense.com[Contact us!]
